config/routes.rb
Rails.application.routes.draw do
  # home
  root to: 'restaurants#index'

  # serve websocket cable requests
  mount ActionCable.server, at: '/cable'

  # route for Twilio SMS
  post '/messages/receive' => 'twilio#receive'

  # users
  devise_for :users, path: '/', path_names: {
    sign_up: 'register',
    sign_in: 'login',
    sign_out: 'logout',
    edit: 'account'
  }
  get '/invoices' => 'users#invoices'
  get '/reservations' => 'users#reservations'

  # restaurant management
  get '/dashboard' => 'dashboard#index'

  # restaurants
  resources :restaurants do
    resources :reservations
    resources :menu_items
    resources :tables
    resources :invoices, except: [:new] do
      resources :orders
    end
    # display all orders
    get 'orders' => 'orders#index'

    resources :walkins, except: [:show, :edit]
    get 'public' => 'walkins#public_show'
    post 'public' => 'walkins#public_create'
    get 'public/new' => 'walkins#public_new', as: 'new_public'

    put 'notify/:id' => 'walkins#notify', as: 'notify'
    put 'requeue/:id' => 'walkins#requeue', as: 'requeue'
    put 'seated/:id' => 'walkins#seated', as: 'seated'
    put 'cancelled/:id' => 'diners#cancelled', as: 'cancelled'
    put 'checked_out/:id' => 'diners#checked_out', as: 'checked_out'

    get 'diners' => 'diners#index'
    get 'diners/:id/edit' => 'diners#edit', as: 'edit_diner'
    get 'diners/:id' => 'diners#show', as: 'diner'
    put 'diners/:id' => 'diners#update'

    put 'reset_queue' => 'restaurants#reset_queue'
  end
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :restaurant, optional: true

  # validates :restaurant_id, presence: true
  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  include AuthenticateRestaurantUser
  include AddBreadcrumbs
  before_action :authenticate_user!, except: [:index, :show, :redirect]
  before_action :set_restaurant_id, except: [:redirect]
  before_action :set_menu_item, only: [:edit, :show, :update, :destroy]
  before_action :check_user_is_part_of_restaurant, except: [:index, :show, :redirect]
  before_action :check_if_invoice_or_reservation_exists, only: [:index]
  helper MenuItemsHelper

  def index
    add_index_breadcrumbs
    gon.restaurant = @restaurant.name
    gon.description = @existing_invoice == '' && @reservation == '' ? 'Takeaway' : 'Order'
      @restaurant_id = params[:restaurant_id]
    if request.fullpath == "/restaurants/#{@restaurant_id}/menu_items?sort=name"
      @menu_items = MenuItem.where(restaurant_id: params[:restaurant_id]).order(:name)
    elsif request.fullpath == "/restaurants/#{@restaurant_id}/menu_items?sort=price"
      @menu_items = MenuItem.where(restaurant_id: params[:restaurant_id]).order(:price)
    elsif request.fullpath == "/restaurants/#{@restaurant_id}/menu_items?sort=description"
      @menu_items = MenuItem.where(restaurant_id: params[:restaurant_id]).order(:description)
    else
      @menu_items = MenuItem.where(restaurant_id: params[:restaurant_id]).order('LOWER(name) ASC')
    end
  end

  def create
    if params[:menu_item][:picture] && params[:menu_item][:picture].path
      uploaded_file = params[:menu_item][:picture].path
      @cloudinary_file = Cloudinary::Uploader.upload(uploaded_file)
    end

    @menu_item = MenuItem.new(menu_item_params)
    @menu_item.restaurant_id = @restaurant.id
    if params[:menu_item][:picture] && params[:menu_item][:picture].path
      @menu_item.picture = @cloudinary_file["secure_url"]
    end
    if @menu_item.save!
      redirect_to restaurant_menu_items_path(@restaurant)
    else
      render :new
    end
  end

  def new
    add_full_breadcrumbs('Menu', restaurant_menu_items_path(@restaurant))
    @menu_item = MenuItem.new
  end

  def edit
    add_full_breadcrumbs('Menu', restaurant_menu_items_path(@restaurant))
  end

  def show
    add_full_breadcrumbs('Menu', restaurant_menu_items_path(@restaurant))
  end

  def update
    if params[:menu_item][:picture] && params[:menu_item][:picture].path
      uploaded_file = params[:menu_item][:picture].path
      @cloudinary_file = Cloudinary::Uploader.upload(uploaded_file)
    end

    if @menu_item.update(menu_item_params)
      if params[:menu_item][:picture] && params[:menu_item][:picture].path
        @menu_item.update(picture: @cloudinary_file["secure_url"])
      end
      redirect_to restaurant_menu_items_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @menu_item.update(restaurant_id: nil)
    redirect_to restaurant_menu_items_path(@restaurant)
  end

  private

  def set_menu_item
    @menu_item = MenuItem.find(params[:id])
  end

  def menu_item_params
    params.require(:menu_item).permit(:name, :price, :description, :ingredients, :tags, :restaurant_id)
  end

  def check_if_invoice_or_reservation_exists
    @existing_invoice = params[:invoice_id] ? params[:invoice_id] : ''
    @reservation = params[:reservation_id] ? params[:reservation_id] : ''
    if params[:invoice_id]
      @table = Invoice.find(params[:invoice_id]).table ? Invoice.find(params[:invoice_id]).table.name : nil
      @is_take_away = false
    elsif params[:reservation_id]
      @is_take_away = false
      if params[:table_id]
        @table = params[:table_id]
      else
        @table = nil
      end
    elsif !current_user
      @is_take_away = true
      @table = nil
    elsif current_user.restaurants.include? @restaurant
      @is_take_away = false
      @table = nil
    else
      @is_take_away = true
      @table = nil
    end
  end
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
  include Format
end

app/views/menu_items/_form.html.erb
<%= form_for menu_item, url: url do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "Name (required)", required: true %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price, placeholder: "Price (required)", min: 0, step: 0.01, required: true %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description, placeholder: "Description (required)", required: true %>
  </div>

  <div class="field">
    <%= f.label :ingredients %>
    <%= f.text_field :ingredients, placeholder: "Ingredients" %>
  </div>

  <div class="field">
    <%= f.label :tags %>
    <%= f.text_field :tags, placeholder: "Tags" %>
  </div>

  <div class="field">
    <%= f.label :picture %>
    <% if menu_item.picture  %>
      <%= cl_image_tag(menu_item.picture, width: 200, height: 100, crop: :fill) %>
    <% end %>
  </div>
  
  <div class="field">
    <%= f.file_field :picture %>
  </div>

  <div class="field">
    <%= f.submit "Save", class: 'waves-effect waves-light btn light-blue lighten-3'%>
  </div>
<% end %>

app/views/menu_items/edit.html.erb
<h1>Edit Menu Item</h1>
<br/>
<%= render "/menu_items/form", menu_item: @menu_item, url: restaurant_menu_item_path(@restaurant) %>

app/views/menu_items/index.html.erb
<div class="row"> <!-- DO NOT TOUCH!! -->

  <!-- ===== LEFT COLUMN: Add order, add menu item, sort by ===== -->
  <div class="col s2">
<center>
  <% if !current_user %>
  <a href='<%= new_user_session_path %>'><button id="takeaway-login" type="button" name="button" class="pulse waves-effect waves-light btn indigo accent-1" style="margin-bottom:5px; margin-top:20px;">Login To Order Takeaway</button></a>
  <% else %>
  <button id="takeaway-show-hide" type="button" name="button" class="pulse waves-effect waves-light btn light-blue lighten-3" style="margin-bottom:5px; margin-top:20px; width:180px;">Order</button>
<% end %>
<br>
<% if current_user && current_user.restaurants.include?(@restaurant) %>
<%= link_to 'Add Menu Item', new_restaurant_menu_item_path(@restaurant.id), class: "waves-effect waves-light btn light-blue accent-4" %>
<% end %>

<br>

<h2>Sort by:</h2>
<a class="waves-effect waves-light btn light-blue lighten-3" href="/restaurants/<%= @restaurant_id %>/menu_items?sort=name" style="width:180px">Name</a><br>
<a class="waves-effect waves-light btn light-blue lighten-3" href="/restaurants/<%= @restaurant_id %>/menu_items?sort=price" style="margin-top:5px; width:180px;">Price</a><br>
<a class="waves-effect waves-light btn light-blue lighten-3" href="/restaurants/<%= @restaurant_id %>/menu_items?ort=description" style="margin-top:5px; width:180px">Description</a>
</center>
</div> <!-- div for left column -->

<!-- ===== MIDDLE COLUMN: display menu items ===== -->
<div class="col s7" id="menu-middle">
  <center><h1>Menu</h1></center>
<div class="all-menu-items">
  <div class="row">
    <% @menu_items.each do |item| %>
      <div class="col s3">
        <p>
        <% if item.picture  %>
          <a href='<%= restaurant_menu_item_path(@restaurant.id, item) %>'><%= cl_image_tag(item.picture, width: 200, height: 100, crop: :fill) %></a>
          <% else %>

          <a href='<%= restaurant_menu_item_path(@restaurant.id, item) %>'><img src="http://img.webmd.com/dtmcms/live/webmd/consumer_assets/site_images/article_thumbnails/quizzes/food_safety_quiz/650x350_food_safety_quiz.jpg" width=200 height=100 style="border-radius:5px"></a>
        <% end %>
      </p>
      <p>
        <b><%= item.name %></b>
      </p>
      <p>
        <%= item.description %>
      </p>
      <p>
        <%= formatPrice(item.price) %>
      </p>

    <button class="add-to-order" style="display:none" type="button" name="button" value='<%= item.id.to_s + '/' + item.name + '/' + item.price.to_s %>'>Add to Order</button>

    <% if current_user && current_user.restaurants.include?(@restaurant) %>
    <%= link_to 'Edit', edit_restaurant_menu_item_path(@restaurant.id, item) %> |
    <%= link_to 'Delete', restaurant_menu_item_path(@restaurant.id, item), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>

      </div>
      <% end %>

</div>
</div>
</div> <!-- div for middle column -->

<!-- ===== RIGHT COLUMN: display submitted orders ===== -->
<div class="col s3">
<div style="display:none" class="ordered-items">
  <% if @is_take_away %>
    <h2>Takeaway</h2>
  <% else %>
    <h2>Your Order</h2>
  <% end %>

  <table class="striped centered">
    <thead>
      <tr>
        <th>-</th>
        <th>No.</th>
        <th>+</th>
        <th>Item</th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody class="ordered-items-list">
    </tbody>
  </table>
<ul class="ordered-items-list">
</ul>
<%= form_for :order, url: restaurant_invoices_path(@restaurant.id), html: {class:'ordered-items-form'} do |f| %>
  <%= label_tag 'Special Requests' %>
  <%= text_field_tag :request, nil, placeholder: 'Special requests' %>
  <%= hidden_field_tag :orders %>
  <%= hidden_field_tag :total_price %>
  <%= hidden_field_tag :is_take_away, @is_take_away, id: "takeaway-tag" %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <% if @is_take_away %>
    <%= label_tag 'Takeaway Time' %><i> (Please allow at least 30 minutes for preparation)</i>
    <%= f.time_select :time, start_hour: (Time.now + 30.minutes).hour, end_hour: 22, ampm: true, minute_step: 15, :required => true %>
      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
      data-name="<%= @restaurant.name %>"
      data-amount=""
      data-description='Order'
      data-locale="auto"
      data-currency="SGD"></script>
  <% elsif @reservation.length > 0 %>
    <%= hidden_field_tag :table_id, @table %>
    <% if @existing_invoice.length > 0 %>
      Invoice: <%= label_tag :invoice, @existing_invoice %>
      <%= hidden_field_tag :invoice_id, @existing_invoice %>
    <% end %>
    <%= hidden_field_tag :reservation_id, @reservation %>
    <%= f.submit 'Create Orders', id: 'create-orders-button'%>
  <% else %>
    Table: <%= label_tag :table_id, @table %>
    <% if @existing_invoice.length > 0 %>
      Invoice: <%= label_tag :invoice, @existing_invoice %>
      <%= hidden_field_tag :invoice_id, @existing_invoice %>
    <% end %>
    <p>
      <%= f.submit 'Create Orders', id: 'create-orders-button'%>
    </p
  <% end %>
<% end %>
</div>

</center>
  <% if @is_take_away %>
    <%= javascript_include_tag('menu_items/takeaway.js') %>
  <% else %>
    <%= javascript_include_tag('menu_items/notTakeaway.js') %>
  <% end %>
</div>

</div> <!-- div for right column -->

</div> <!-- div for row class DO NOT TOUCH!! -->

app/views/menu_items/index2.html.erb
<div class="container">

<h1>Menu</h1>
<% if current_user && current_user.restaurants.include?(@restaurant) %>
<%= link_to 'Add Menu Item', new_restaurant_menu_item_path(@restaurant.id), class: "waves-effect waves-light btn light-blue accent-4"%>
<% end %>

  <% if !current_user %>
  <a href='<%= new_user_session_path %>'><button id="takeaway-login" type="button" name="button" class="waves-effect waves-light btn light-blue lighten-3">Login To Order Takeaway</button></a>
  <% else %>
  <button id="takeaway-show-hide" type="button" name="button" class="waves-effect waves-light btn light-blue lighten-3">Order</button>
<% end %>

</div>
<br>

<center>
<h1>Sort by:</h1>
<a class="waves-effect waves-light btn light-blue lighten-3" href="/restaurants/<%= @restaurant_id %>/menu_items?name=sort">Name</a>
<a class="waves-effect waves-light btn light-blue lighten-3" href="/restaurants/<%= @restaurant_id %>/menu_items?price=sort">Price</a>
<a class="waves-effect waves-light btn light-blue lighten-3" href="/restaurants/<%= @restaurant_id %>/menu_items?description=sort">Description</a>
<a class="waves-effect waves-light btn light-blue lighten-3" href="/restaurants/<%= @restaurant_id %>/menu_items?ingredient=sort">Ingredient</a>
<a class="waves-effect waves-light btn light-blue lighten-3" href="/restaurants/<%= @restaurant_id %>/menu_items?tag=sort">Tag</a><br><br>





<div class="all-menu-items">
<% @menu_items.each do |item| %>
<div>
  <p>
    <% if item.picture  %>
      <a href='<%= restaurant_menu_item_path(@restaurant.id, item) %>'><%= cl_image_tag(item.picture, width: 200, height: 100, crop: :fill) %></a>
    <% end %>
  </p>
  <p>
    Name:
    <%= item.name %>
  </p>
  <p>
    Description:
    <%= item.description %>
  </p>
  <p>
    Price:
    <%= formatPrice(item.price) %>
  </p>
</div>

<button class="add-to-order" style="display:none" type="button" name="button" value='<%= item.id.to_s + '/' + item.name + '/' + item.price.to_s %>'>Add to Order</button>

<% if current_user && current_user.restaurants.include?(@restaurant) %>
<%= link_to 'Edit', edit_restaurant_menu_item_path(@restaurant.id, item) %> |
<%= link_to 'Destroy', restaurant_menu_item_path(@restaurant.id, item), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>



<br>
<br>

<% end %>
</div>

<div style="display:none" class="ordered-items">
<ul class="ordered-items-list">
</ul>

<%= form_for :order, url: restaurant_invoices_path(@restaurant.id), html: {class:'ordered-items-form'} do |f| %>
  <%= label_tag 'Special Requests' %>
  <%= text_field_tag :request, nil, placeholder: 'Special requests' %>
  <%= hidden_field_tag :orders %>
  <%= hidden_field_tag :total_price %>
  <%= hidden_field_tag :is_take_away, @is_take_away %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <% if !current_user || !current_user.restaurants.include?(@restaurant) %>
  <%= label_tag 'Takeaway Time' %><i> (Please allow at least 30 minutes for preparation)</i>
  <%= f.time_select :time, start_hour: (Time.now + 30.minutes).hour, end_hour: 22, ampm: true, minute_step: 15, :required => true %>
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="<%= @restaurant.name %>"
    data-amount=""
    data-description='Order'
    data-locale="auto"
    data-currency="SGD"></script>
  <% else %>
    Table: <%= label_tag :table_id, @table %>
    <% if @existing_invoice.length > 0 %>
      Invoice: <%= label_tag :invoice, @existing_invoice %>
      <%= hidden_field_tag :invoice_id, @existing_invoice %>
    <% end %>
    <%= f.submit 'Create Orders', id: 'create-orders-button'%>
  <% end %>
<% end %>
</div>

</center>
<%= javascript_include_tag('menu_items/takeaway.js') %>
</div>

app/views/menu_items/new.html.erb
<div class="container">
<h1>New Menu Item</h1>
<br/>
<%= render "/menu_items/form", menu_item: @menu_item, url: restaurant_menu_items_path(@restaurant) %>
</div>

app/views/menu_items/show.html.erb
<div class="container">
<h1><%= @menu_item.name %></h1>
<p>
  <% if @menu_item.picture  %>
    <%= cl_image_tag(@menu_item.picture, width: 200, height: 100, crop: :fill) %>
    <% else %>
    <img src="http://img.webmd.com/dtmcms/live/webmd/consumer_assets/site_images/article_thumbnails/quizzes/food_safety_quiz/650x350_food_safety_quiz.jpg" width=200 height=100>
  <% end %>
</p>
<p>
  <%= @menu_item.description %>
</p>
<p>
  <%= formatPrice(@menu_item.price) %>
</p>
<p>
  <%= @menu_item.ingredients %>
</p>
<p>
  <%= @menu_item.tags %>
</p>
</div>

app/views/menu_items/spare.html.erb
<%= link_to "Back to Restaurant", restaurant_path(@restaurant) %> <br> <br>
<div class="row"> <!-- DO NOT TOUCH!! -->

  <!-- ===== LEFT COLUMN: Add order, add menu item, sort by ===== -->
  <div class="col s2" id="menu-left">

  <% if !current_user %>
  <a href='<%= new_user_session_path %>'><button id="takeaway-login" type="button" name="button" class="waves-effect waves-light btn light-blue lighten-3" style="margin-bottom:5px; margin-top:20px;">Login To Order Takeaway</button></a>
  <% else %>
  <button id="takeaway-show-hide" type="button" name="button" class="pulse waves-effect waves-light btn light-blue lighten-3" style="margin-bottom:5px; margin-top:20px;">Order</button>
<% end %>
<br>
<% if current_user && current_user.restaurants.include?(@restaurant) %>
<%= link_to 'Add Menu Item', new_restaurant_menu_item_path(@restaurant.id), class: "waves-effect waves-light btn light-blue accent-4" %>
<% end %>

<br>

<h2>Sort by:</h2>
<a class="waves-effect waves-light btn light-blue lighten-3" href="/restaurants/<%= @restaurant_id %>/menu_items?name=sort">Name</a><br>
<a class="waves-effect waves-light btn light-blue lighten-3" href="/restaurants/<%= @restaurant_id %>/menu_items?price=sort" style="margin-top:5px">Price</a><br>
<a class="waves-effect waves-light btn light-blue lighten-3" href="/restaurants/<%= @restaurant_id %>/menu_items?description=sort" style="margin-top:5px">Description</a>

</div> <!-- div for left column -->

<!-- ===== MIDDLE COLUMN: display menu items ===== -->
<div class="col s7" id="menu-left">
  <center><h1>Menu Items</h1></center>

<div class="all-menu-items">

  <div class="row">

    <% @menu_items.each do |item| %>
    <div>
      <p>
        <% if item.picture  %>
          <a href='<%= restaurant_menu_item_path(@restaurant.id, item) %>'><%= cl_image_tag(item.picture, width: 200, height: 100, crop: :fill) %></a>
        <% end %>
      </p>
      <p>
        Name:
        <%= item.name %>
      </p>
      <p>
        Description:
        <%= item.description %>
      </p>
      <p>
        Price:
        <%= formatPrice(item.price) %>
      </p>
    </div>

    <button class="add-to-order" style="display:none" type="button" name="button" value='<%= item.id.to_s + '/' + item.name + '/' + item.price.to_s %>'>Add to Order</button>

    <% if current_user && current_user.restaurants.include?(@restaurant) %>
    <%= link_to 'Edit', edit_restaurant_menu_item_path(@restaurant.id, item) %> |
    <%= link_to 'Destroy', restaurant_menu_item_path(@restaurant.id, item), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>

      </div>
      <% end %>
</div>

</div> <!-- div for middle column -->

<!-- ===== RIGHT COLUMN: display submitted orders ===== -->
<div class="col s3">
<div style="display:none" class="ordered-items">
<ul class="ordered-items-list">

<%= form_for :order, url: restaurant_invoices_path(@restaurant.id), html: {class:'ordered-items-form'} do |f| %>
  <%= label_tag 'Special Requests' %>
  <%= text_field_tag :request, nil, placeholder: 'Special requests' %>
  <%= hidden_field_tag :orders %>
  <%= hidden_field_tag :total_price %>
  <%= hidden_field_tag :is_take_away, @is_take_away %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <% if !current_user || !current_user.restaurants.include?(@restaurant) %>
  <%= label_tag 'Takeaway Time' %><i> (Please allow at least 30 minutes for preparation)</i>
  <%= f.time_select :time, start_hour: (Time.now + 30.minutes).hour, end_hour: 22, ampm: true, minute_step: 15, :required => true %>
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="<%= @restaurant.name %>"
    data-amount=""
    data-description='Order'
    data-locale="auto"
    data-currency="SGD"></script>
  <% else %>
    Table: <%= label_tag :table_id, @table %>
    <% if @existing_invoice.length > 0 %>
      Invoice: <%= label_tag :invoice, @existing_invoice %>
      <%= hidden_field_tag :invoice_id, @existing_invoice %>
    <% end %>
    <%= f.submit 'Create Orders', id: 'create-orders-button'%>
  <% end %>
<% end %>
</div>

</div> <!-- div for right column -->
<%= javascript_include_tag('menu_items/takeaway.js') %>

</div> <!-- div for row class DO NOT TOUCH!! -->