config/routes.rb
Rails.application.routes.draw do
  # home
  root to: 'restaurants#index'

  # serve websocket cable requests
  mount ActionCable.server, at: '/cable'

  # route for Twilio SMS
  post '/messages/receive' => 'twilio#receive'

  # users
  devise_for :users, path: '/', path_names: {
    sign_up: 'register',
    sign_in: 'login',
    sign_out: 'logout',
    edit: 'account'
  }
  get '/invoices' => 'users#invoices'
  get '/reservations' => 'users#reservations'

  # restaurant management
  get '/dashboard' => 'dashboard#index'

  # restaurants
  resources :restaurants do
    resources :reservations
    resources :menu_items
    resources :tables
    resources :invoices, except: [:new] do
      resources :orders
    end
    # display all orders
    get 'orders' => 'orders#index'

    resources :walkins, except: [:show, :edit]
    get 'public' => 'walkins#public_show'
    post 'public' => 'walkins#public_create'
    get 'public/new' => 'walkins#public_new', as: 'new_public'

    put 'notify/:id' => 'walkins#notify', as: 'notify'
    put 'requeue/:id' => 'walkins#requeue', as: 'requeue'
    put 'seated/:id' => 'walkins#seated', as: 'seated'
    put 'cancelled/:id' => 'diners#cancelled', as: 'cancelled'
    put 'checked_out/:id' => 'diners#checked_out', as: 'checked_out'

    get 'diners' => 'diners#index'
    get 'diners/:id/edit' => 'diners#edit', as: 'edit_diner'
    get 'diners/:id' => 'diners#show', as: 'diner'
    put 'diners/:id' => 'diners#update'

    put 'reset_queue' => 'restaurants#reset_queue'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  has_many :menu_items, through: :orders
  has_many :orders
  belongs_to :reservation, optional: true
  belongs_to :restaurant
  belongs_to :table, optional: true
  belongs_to :user, optional: true

  validates :restaurant_id, presence: true
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :restaurant, optional: true

  # validates :restaurant_id, presence: true
  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :invoice
  belongs_to :menu_item
  has_one :restaurant, through: :invoice
  belongs_to :user, optional: true

  # validates :menu_item_id, presence: true
  # validates :invoice_id, presence: true
  # validates :is_take_away, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :invoice, optional: true
  belongs_to :restaurant
  belongs_to :table, optional: true
  belongs_to :user, optional: true

  validates :name, presence: true
  validates :party_size, presence: true
  validates :restaurant_id, presence: true
  # validates :start_time, presence: true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :invoices
  has_many :menu_items
  has_many :ordered_items, through: :orders, source: :menu_item
  has_many :orders, through: :invoices
  has_many :reservations
  has_many :tables
  has_many :reviews
  has_and_belongs_to_many :users

  validates :name, presence: true
  validates :address1, presence: true
  validates :address_city, presence: true
  validates :address_country, presence: true
  validates :address_postal, presence: true
  # validates :description, presence: true
  validates :cuisine, presence: true
end

app/models/table.rb
class Table < ApplicationRecord
  has_many :invoices
  belongs_to :restaurant, optional: true
  has_many :reservations


  # validates :restaurant_id, presence: true
  validates :name, presence: true
  validates :capacity_total, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :invoices
  has_and_belongs_to_many :restaurants
  has_many :reviews
  has_many :reservations
  has_many :orders, through: :invoices

  validates :name, presence: true
  validates :email, presence: true
  validates :phone, presence: true
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/diner_helper.rb
module DinerHelper
  include Format
end

app/helpers/invoices_helper.rb
module InvoicesHelper
  include Format
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
  include Format
end

app/helpers/order_helper.rb
module OrderHelper
  include Format
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/twilio_helper.rb
module TwilioHelper
end

app/helpers/users_helper.rb
module UsersHelper
  include Format
end

app/helpers/walkin_helper.rb
module WalkinHelper
  include Format
end

app/views/partials/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/partials/_nav.html.erb
<!-- dropdown menu -->
<ul id="dropdown2" class="dropdown-content">
    <% if current_user && current_user.restaurant_id %>
    <li><%= link_to 'Orders', restaurant_orders_path(current_user.restaurant_id), :class => 'navbar-link' %></li>
    <li><%= link_to 'Invoices', restaurant_invoices_path(current_user.restaurant_id), :class => 'navbar-link' %></li>
    <li><%= link_to 'Menu', restaurant_menu_items_path(current_user.restaurant_id), :class => 'navbar-link' %></li>
    <li><%= link_to 'Edit Restaurant', edit_restaurant_path(current_user.restaurant_id), :class => 'navbar-link' %></li>
    <%end%>
    <li class="divider"></li>
    <li><a href="/invoices">My Invoices</a></li>
    <li><a href="/reservations">My Reservations</a></li>
    <li><a href="/account">My Profile</a></li>
    <li class="divider"></li>
    <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
</ul>

<!-- nav bar itself -->
<nav>
  <div class="nav-wrapper light-blue lighten-3">
    <!-- left side (logo and dropdown) -->
    <ul id="nav-mobile" class="left hide-on-med-and-down valign-wrapper">
      <li>
        <a href="/" class="brand-logo" id="rex-logo"><img src="<%= asset_path 'rex.png' %>" height="35" width="35" style="margin-top: 10px; margin-left:18px"></a>
      </li>
    </ul>
 <a href="/" class="brand-logo center" id="logo">locavorus</a>
      <!-- right side of nav -->
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if user_signed_in? %>
        <% if current_user.restaurant_id %>
          <li><%= link_to 'Dashboard', dashboard_path, :class => 'navbar-link', id: 'footer-text' %></li>
        <% end %>
        <li>
          <a class="dropdown-button" data-beloworigin="true" href="#!" data-constrainWidth="false" data-activates="dropdown2" id="footer-text">Account<i class="material-icons right">arrow_drop_down</i>
          </a>
        </li>
      <% else %>
        <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link', id: 'footer-text' %></li>
        <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link', id: 'footer-text'  %></li>
      <% end %>
    </ul>
  </div>
</nav>

<!-- ===== BREADCRUMBS & SEARCH BAR ===== -->
<p style="margin-left:15px; font-size:18px;" id="footer-text"> <%= render_breadcrumbs :separator => ' / ' %> </p>

<div id="search-bar">
  <form class="" action="/restaurants" method="get" style="display:inline-block;">
    <table>
      <tr>
        <td><p style="margin-bottom:38px" id="footer-text">Find</p></td>
        <td><input type="text" name="search" value="" id="footer-text" placeholder="restaurants & cuisines"></td>
        <td><p style="margin-bottom:38px" id="footer-text">In</p></td>
        <td><input type="text" name="city" value="" id="footer-text" placeholder="Singapore"></td>
        <td><button type="submit" class="waves-effect waves-light btn pink accent-1" style="margin-bottom:12px">Search</button></td>
      </tr>
    </table>
  </form>
</div>
<br>
<!-- end of search bar -->

app/views/partials/spare.html.erb
<!-- ===== SEARCH BAR ===== -->
    <form id="search-field">
      <div class="input-field">
        <input id="search" type="search" required placeholder="Search for a restaurant">
        <label class="label-icon" for="search"><i class="material-icons">search</i></label>
        <i class="material-icons">close</i>
      </div>
    </form>
  <!-- end of search bar -->


<!-- ===== OLD BULMA NAV BAR CODE START ===== -->

<nav class="nav">
  <div class="nav-left">
    <a class="nav-item" href="/">
      Locavorus
    </a>
  </div>

  <div class="nav-center">
    <div class="field is-grouped">
        <form class="" action="/restaurants" method="get">
          <!-- <p class="control"> -->
          <input type="text" name="search" value="" placeholder="Search">
        <!-- </p> -->
        <!-- <p class="control"> -->
          <input type="text" name="city" value="" placeholder="Location">
        <!-- </p> -->
        <!-- <p class="control"> -->
        <button type="submit">Search</button>
        </form>
      </p>
    </div>
  </div>

  <div class="nav-right nav-menu">
    <% if user_signed_in? %>
  <% if current_user[:restaurant_id]  %>
  <li class="nav-item is-tab">
    <%= link_to 'Dashboard', dashboard_path, :class => 'navbar-link' %>
  </li>
  <% end %>
  <li class="nav-item is-tab">
    <%= link_to 'Account', edit_user_registration_path, :class => 'navbar-link' %>
  </li>
  <li class="nav-item is-tab">
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  </li>
<% else %>
  <li class="nav-item is-tab">
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
  </li>
  <li class="nav-item is-tab">
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  </li>
<% end %>
  </div>

<!-- ===== OLD BULMA NAV BAR CODE END ===== -->

<!-- center portion -->
<div class="center">
      <input type="text" name="Search" value="" placeholder="Search">
      <input type="text" name="Location" value="" placeholder="Location">

    <a href="/restaurants">Search</a>
    <!-- <span class="nav-item icon">
    <i class="fa fa-search" aria-hidden="true"></i>
    </span> -->
</div>

<!-- ======= LAST TIME ONE ======= -->
  <div class="nav-center">
    <div class="field is-grouped">
      <p class="control">
        <input type="text" name="Search" value="" placeholder="Search">
      </p>
      <p class="control">
        <input type="text" name="Location" value="" placeholder="Location">
      </p>
      <p class="control">

      <a href="/restaurants">Search</a>
      <!-- <span class="nav-item icon">
      <i class="fa fa-search" aria-hidden="true"></i>
      </span> -->
      </p>
    </div>
  </div>

  <div class="nav-right nav-menu">
    <% if user_signed_in? %>
  <% if current_user[:restaurant_id]  %>
  <li class="nav-item is-tab">
    <%= link_to 'Dashboard', dashboard_path, :class => 'navbar-link' %>
  </li>
  <% end %>
  <li class="nav-item is-tab">
    <%= link_to 'Account', edit_user_registration_path, :class => 'navbar-link' %>
  </li>
  <li class="nav-item is-tab">
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  </li>
<% else %>
  <li class="nav-item is-tab">
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
  </li>
  <li class="nav-item is-tab">
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  </li>
<% end %>
  </div>

    <!--https://jsfiddle.net/crabbly/218o6g2g/-->
    <!--http://codepen.io/tdaved/pen/XdxJZZ-->

  </div>
</nav>

app/views/shared/_nav.html.erb
<nav class="nav">
  <div class="nav-left">
    <a class="nav-item" href="/">
      Locavorus
    </a>
  </div>

  <div class="nav-center">

    <% if !@is_main%>

    <div class="field is-grouped">
      <p class="control">
        <input type="text" name="Search" value="" placeholder="Search">
      </p>
      <p class="control">
        <input type="text" name="Location" value="" placeholder="Location">
      </p>
      <p class="control">

      <a href="/restaurants">Search</a>
      <!-- <span class="nav-item icon">
      <i class="fa fa-search" aria-hidden="true"></i>
      </span> -->
      </p>
    </div>

    <% end %>
  </div>

  <div class="nav-right nav-menu">
    <a class="nav-item is-tab" href="/account">
      Profile
    </a>
    <a class="nav-item" href="/signup">
      Signup
    </a>
    <a class="nav-item" href="/login">
      Login
    </a>
    <a class="nav-item">
      Logout
    </a>
  </div>

</nav>