config/routes.rb
Rails.application.routes.draw do
  # home
  root to: 'restaurants#index'

  # serve websocket cable requests
  mount ActionCable.server, at: '/cable'

  # route for Twilio SMS
  post '/messages/receive' => 'twilio#receive'

  # users
  devise_for :users, path: '/', path_names: {
    sign_up: 'register',
    sign_in: 'login',
    sign_out: 'logout',
    edit: 'account'
  }
  get '/invoices' => 'users#invoices'
  get '/reservations' => 'users#reservations'

  # restaurant management
  get '/dashboard' => 'dashboard#index'

  # restaurants
  resources :restaurants do
    resources :reservations
    resources :menu_items
    resources :tables
    resources :invoices, except: [:new] do
      resources :orders
    end
    # display all orders
    get 'orders' => 'orders#index'

    resources :walkins, except: [:show, :edit]
    get 'public' => 'walkins#public_show'
    post 'public' => 'walkins#public_create'
    get 'public/new' => 'walkins#public_new', as: 'new_public'

    put 'notify/:id' => 'walkins#notify', as: 'notify'
    put 'requeue/:id' => 'walkins#requeue', as: 'requeue'
    put 'seated/:id' => 'walkins#seated', as: 'seated'
    put 'cancelled/:id' => 'diners#cancelled', as: 'cancelled'
    put 'checked_out/:id' => 'diners#checked_out', as: 'checked_out'

    get 'diners' => 'diners#index'
    get 'diners/:id/edit' => 'diners#edit', as: 'edit_diner'
    get 'diners/:id' => 'diners#show', as: 'diner'
    put 'diners/:id' => 'diners#update'

    put 'reset_queue' => 'restaurants#reset_queue'
  end
end

app/controllers/diners_controller.rb
class DinersController < ApplicationController
  include AuthenticateRestaurantUser
  include FindingTableLogic
  include SendTwilio
  include Format
  before_action :authenticate_user!
  before_action :set_restaurant
  before_action :check_user_is_part_of_restaurant
  before_action :set_diner, only: %i[show edit update]
  before_action :set_duration

  def index
    add_breadcrumb "Restaurants", :restaurants_path
    add_breadcrumb @restaurant.name, restaurant_path(@restaurant)
    @diners = Reservation.where(restaurant_id: params[:restaurant_id], status: 'dining').or(Reservation.where(restaurant_id: params[:restaurant_id], status: 'awaiting'))
  end

  def edit
    add_breadcrumb "Restaurants", :restaurants_path
    add_breadcrumb @restaurant.name, restaurant_path(@restaurant)

    tables_occupied = Reservation.where(restaurant_id: @restaurant.id).where(status: 'dining').where.not(table_id: nil).map do |reservation|
      reservation.table
    end
    all_tables = @restaurant.tables
    tables_avail = all_tables - tables_occupied
    @table_options = tables_avail.map do |table|
      [table.name, table.id]
    end
    # @table_options = @restaurant.tables.where(capacity_current: 0).map do |table|
    #   [table.name, table.id]
    # end
    if @diner.table != nil and @diner.status == 'dining'
      @table_options << [@diner.table.name, @diner.table.id]
    end
    @table_options << ['', nil]
  end

  def show
    add_breadcrumb "Restaurants", :restaurants_path
    add_breadcrumb @restaurant.name, restaurant_path(@restaurant)
  end

  def update
    old_party_size = @diner.party_size
    old_table_id = @diner.table_id
    old_start_time = @diner.start_time

#Check if change in table / party size is possible in next status
    if @diner.status == 'queuing' && @diner.table_id == nil && params[:reservation][:status] == 'cancelled'
      @diner.status = params[:reservation][:status]
      save_update(@diner)
######### Diner was QUEUING
    elsif @diner.status == 'queuing'
      if params[:reservation][:status] == 'queuing' or params[:reservation][:status] == 'awaiting'
        set_values(@diner, params[:reservation][:party_size], nil, nil)

        if params[:reservation][:table_id] != '' and params[:reservation][:table_id] != nil

          table = determine_table(@restaurant, [Table.find(params[:reservation][:table_id])], @diner, Time.now, @est_duration)

          if table
            assign_table(@diner, table)

            set_values(@diner, params[:reservation][:party_size], table.id, Time.now)

            @diner.start_time = Time.now
            @diner.end_time = Time.now + @est_duration

            if params[:reservation][:status] == 'awaiting'
              @diner.status = 'awaiting'
              sms_awaiting(@diner)
              save_update(@diner)
            else
              save_update(@diner)
            end

          else
            set_values(@diner, old_party_size, old_table_id, Time.now)

            flash['alert'] = 'New parameters not permitted.'
            tables_occupied = Reservation.where(restaurant_id: @restaurant.id).where(status: 'dining').where.not(table_id: nil).map do |reservation|
              reservation.table
            end
            all_tables = @restaurant.tables
            tables_avail = all_tables - tables_occupied
            @table_options = tables_avail.map do |table|
              [table.name, table.id]
            end
            if @diner.table != nil
              @table_options << [@diner.table.name, @diner.table.id]
            end
            @table_options << ['', nil]
            render :edit
          end
        else
          if old_table_id != nil
            old_table = Table.find(old_table_id)
            if old_table != nil
              old_table.capacity_current = 0
              old_table.save!
            end
          end
          @diner.table = nil
          save_update(@diner)
        end

      elsif params[:reservation][:status] == 'cancelled'
        @diner.status = 'cancelled'
        @diner.end_time = Time.now
        @diner.save
        sms_cancelled(@diner)
        reassign_table(@diner, @restaurant)
        save_update(@diner)
      end

####### Diner was AWAITING or DINING
    elsif @diner.status == 'awaiting' || @diner.status == 'dining'

      if params[:reservation][:status] == 'dining' or params[:reservation][:status] == 'awaiting'
        # @diner.party_size = params[:reservation][:party_size]
        set_values(@diner, params[:reservation][:party_size], nil, nil)

        if params[:reservation][:table_id] != '' and params[:reservation][:table_id] != nil
          table = determine_table(@restaurant, [Table.find(params[:reservation][:table_id])], @diner, Time.now, @est_duration)

          if table

            assign_table(@diner, table)

            set_values(@diner, params[:reservation][:party_size], table.id, Time.now)

            if params[:reservation][:status] == 'dining'
              @diner.status = 'dining'

              save_update(@diner)
            elsif params[:reservation][:status] == 'awaiting'
              @diner.status = 'awaiting'
              save_update(@diner)
            end

          else
            set_values(@diner, old_party_size, old_table_id, Time.now)

            flash['alert'] = 'New parameters not permitted.'
            tables_occupied = Reservation.where(restaurant_id: @restaurant.id).where(status: 'dining').where.not(table_id: nil).map do |reservation|
              reservation.table
            end
            all_tables = @restaurant.tables
            tables_avail = all_tables - tables_occupied
            @table_options = tables_avail.map do |table|
              [table.name, table.id]
            end
            if @diner.table != nil
              @table_options << [@diner.table.name, @diner.table.id]
            end
            @table_options << ['', nil]
            render :edit
          end
        else
          set_values(@diner, params[:reservation][:party_size], params[:reservation][:table_id], Time.now)

          if params[:reservation][:status] == 'dining'
            @diner.status = 'dining'
            save_update(@diner)
          elsif params[:reservation][:status] == 'awaiting'
            @diner.status = 'awaiting'
            save_update(@diner)
          end
        end
      elsif params[:reservation][:status] == 'cancelled' || params[:reservation][:status] == 'queuing' || params[:reservation][:status] == 'checked_out'
        reassign_table(@diner, @restaurant)
        if params[:reservation][:status] == 'cancelled'

          @diner.status = 'cancelled'
          @diner.end_time = Time.now
          @diner.save
          sms_cancelled(@diner)
          reassign_table(@diner, @restaurant)


        elsif params[:reservation][:status] == 'queuing'
          @diner.start_time = nil
          @diner.end_time = nil
          @diner.save
          reassign_table(@diner, @restaurant)
          @diner.status = 'queuing'

          # send to back of queue (requeue)
          @diner.table_id = nil
          @diner.queue_number = @diner.restaurant.next_queue_number
          @diner.restaurant.next_queue_number += 1
          @diner.restaurant.save!
          sms_send_back_queue(@diner)

        elsif params[:reservation][:status] == 'checked_out'
          @diner.status = 'checked_out'
          @diner.end_time = Time.now
          @diner.save
          reassign_table(@diner, @restaurant)
        end
        save_update(@diner)
      end
######## DINER was on RESERVATION (editable status only)
      elsif @diner.status == 'reservation'
        if params[:reservation][:status] == 'reservation'
          save_update(@diner)
        elsif params[:reservation][:status] == 'dining'
          if @diner.table.capacity_current = 0
            @diner.status = 'dining'
            save_update(@diner)
          else
            flash['alert'] = 'The table is currently occupied.'
            tables_occupied = Reservation.where(restaurant_id: @restaurant.id).where(status: 'dining').where.not(table_id: nil).map do |reservation|
              reservation.table
            end
            all_tables = @restaurant.tables
            tables_avail = all_tables - tables_occupied
            @table_options = tables_avail.map do |table|
              [table.name, table.id]
            end
            if @diner.table != nil
              @table_options << [@diner.table.name, @diner.table.id]
            end
            @table_options << ['', nil]
            render :edit
          end
        elsif params[:reservation][:status] == 'cancelled'
          @diner.status = 'cancelled'
          @diner.table_id = nil
          @diner.end_time = nil

          subject = "Reservation at #{@diner.restaurant.name} on #{formatOrderDate(@diner.start_time)} for #{@diner.party_size}"

          GmailerMailer.send_reservation_delete(@diner, @diner.email, subject).deliver_later

          save_update(@diner)
        end
    end
  end

  def reassign_table(diner, restaurant)
    next_customer = find_next_customer(diner.table)
    if next_customer
      # Check if current table has reservations that will clash
      next_customer_table = determine_table(restaurant, [diner.table], next_customer, Time.now, 2.hours)
      if next_customer_table

        assign_table(next_customer, next_customer_table)
        diner.table = nil
        diner.save!
      else
        reset_table_count(diner.table.id) if diner.table
      end
    else
      reset_table_count(diner.table.id) if diner.table
    end
  end

  # Update leaving customer
  def save_update(diner)
    if diner.save!
      flash['notice'] = 'Successfully updated parameters.'
      redirect_to dashboard_path
    else
      flash['alert'] = 'Error 500. Unable to save lastest changes.'
      tables_occupied = Reservation.where(restaurant_id: @restaurant.id).where(status: 'dining').where.not(table_id: nil).map do |reservation|
        reservation.table

app/helpers/diner_helper.rb
module DinerHelper
  include Format
end

app/views/diners/edit.html.erb
<div class="container">
<h1>Edit Diner</h1>

<% if @diner.status == 'reservation' %>
  <%= link_to "Edit Reservation",edit_restaurant_reservation_path(@restaurant, @diner)%>
<% end %>

<%= form_for @diner, url: restaurant_diner_path(@restaurant, @diner), html: {method: :put} do |f| %>

  <div class="field">
    Name:
    <%= @diner.name %>
  </div>

  <div class="field">
    Phone:
    <%= @diner.phone %>
  </div>

  <div class="field">
    Email:
    <%= @diner.email %>
  </div>

  <div class="field">
    Queue Number:
    <%= @diner.queue_number %>
  </div>

  <% if @diner.status == 'queuing' %>
  <% if @diner.table %>
    <div class="field">
      <%= f.label :status, "Status" %>
      <%= f.select(:status, [['Cancelled','cancelled'],['Queuing','queuing'], ['Awaiting','awaiting']])%>
    </div>
  <% else %>
    <div class="field">
      <%= f.label :status, "Status" %>
      <%= f.select(:status, [['Cancelled','cancelled'],['Queuing','queuing']])%>
    </div>
  <% end %>
  <% elsif @diner.status == 'reservation' %>
  <div class="field">
    <%= f.label :status, "Status" %>
    <%= f.select(:status, [['Cancelled','cancelled'],['Reservation','reservation'], ['Dining','dining']])%>
  </div>
  <% elsif @diner.status == 'awaiting' %>
  <div class="field">
    <%= f.label :status, "Status" %>
    <%= f.select(:status, [['Cancelled','cancelled'], ['Queuing','queuing'], ['Awaiting','awaiting'], ['Dining','dining']])%>
  </div>
  <% elsif @diner.status == 'dining' %>
  <div class="field">
    <%= f.label :status, "Status" %>
    <%= f.select(:status, [['Awaiting','awaiting'], ['Dining','dining'], ['Checked Out','checked_out']])%>
  </div>
  <% end %>

  <% if @diner.status == 'reservation' %>
  <div class="field">
    Party Size:
    <%= @diner.party_size %>
  </div>
  <% else %>
  <div class="field">
    <%= f.label :party_size, "Number of Diners" %>
    <% if @restaurant.tables.count > 0 %>
      <%= f.select :party_size,[*1..@restaurant.tables.reject{|y| y[:capacity_total] == nil}.max_by{|x| x[:capacity_total]}.capacity_total]%>
    <% else %>
      <%= f.select :party_size,[0]%>
    <% end %>
  </div>
  <% end %>

  <% if @diner.status == 'reservation'%>
  <div class="field">
    Table:
    <% if @diner.table_id != nil %>
      <%= @diner.table.name %>
    <% end %>
  </div>
  <% else %>
  <div class="field">
    <%= f.label :table_id, "Table" %>
    <%= f.select(:table_id, @table_options)%>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :special_requests, "Special Requests" %>
    <%= f.text_field :special_requests, placeholder: "Special Requests"%>
  </div>

  <div class="field">
    Start Time:
    <%= @diner.start_time %>
  </div>

  <div class="field">
    End Time:
    <%= @diner.end_time %>
  </div>

  <%= f.submit "Submit", class: 'waves-effect waves-light btn light-blue lighten-3' %>
<% end %>
</div>

app/views/diners/index.html.erb
<div class="container">
<h1>Diners</h1>
<p>Current Time: <%= formatOrderDate(Time.now)%></p>

<h2>Notified</h2>
<table class="striped centered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Quantity</th>
      <th>Status</th>
      <th>Queue Number</th>
      <th>Table</th>
      <th>Requests</th>
      <th>Start Time</th>
      <th>Est End Time</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @diners.where(status:'awaiting').each do |diner| %>
    <tr>
      <td><%= link_to diner.name, restaurant_edit_diner_path(@restaurant.id, diner) %></td>
      <td><%= diner.phone %></td>
      <td><%= diner.email %></td>
      <td><%= diner.party_size %></td>
      <td>
        <% if diner.status == 'awaiting' %>
        <font color="red"><b><%= diner.status %></b></font>
        <% else %>
        <%= diner.status %>
        <% end %>
      </td>
      <td><%= diner.queue_number %></td>
      <td>
        <% if diner.table_id != nil %>
        <%= Table.find(diner.table_id).name %>
        <% end %>
      </td>
      <td><%= diner.special_requests %></td>
      <td>
        <% if diner.start_time != nil %>
        <%= formatOrderDate(diner.start_time.getlocal('+08:00')) %>
        <% end %>
      </td>
      <td>
        <% if diner.end_time %>
        <% if Time.now > diner.end_time %>
        <font color="red"><b><%= formatOrderDate(diner.end_time.getlocal('+08:00')) %></b></font>
        <% else %>
        <%= formatOrderDate(diner.end_time.getlocal('+08:00')) %>
        <% end %>
        <% end %>
      </td>
      <td>
        <%= link_to 'Seated', restaurant_seated_path(@restaurant, diner), method: :put %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<h2>Current</h2>
<table class="striped centered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Quantity</th>
      <th>Status</th>
      <th>Queue Number</th>
      <th>Table</th>
      <th>Requests</th>
      <th>Start Time</th>
      <th>Est End Time</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @diners.where(status:'dining').each do |diner| %>
    <tr>
      <!-- <td><%= link_to diner.name, restaurant_diner_path(@restaurant.id, diner) %></td> -->
      <td><%= link_to diner.name, restaurant_edit_diner_path(@restaurant.id, diner) %></td>
      <td><%= diner.phone %></td>
      <td><%= diner.email %></td>
      <td><%= diner.party_size %></td>
      <td>
        <% if diner.status == 'awaiting' %>
        <font color="red"><b><%= diner.status %></b></font>
        <% else %>
        <%= diner.status %>
        <% end %>
      </td>
      <td><%= diner.queue_number %></td>
      <td>
        <% if diner.table_id != nil %>
        <%= Table.find(diner.table_id).name %>
        <% end %>
      </td>
      <td><%= diner.special_requests %></td>
      <td>
        <% if diner.start_time != nil %>
        <%= formatOrderDate(diner.start_time.getlocal('+08:00')) %>
        <% end %>
      </td>
      <td>
        <% if diner.end_time %>
        <% if Time.now > diner.end_time %>
        <font color="red"><b><%= formatOrderDate(diner.end_time.getlocal('+08:00')) %></b></font>
        <% else %>
        <%= formatOrderDate(diner.end_time.getlocal('+08:00')) %>
        <% end %>
        <% end %>
      </td>
      <td>
        <%= link_to 'Check Out', restaurant_checked_out_path(@restaurant, diner), method: :put, data: { confirm: 'This will check the customer out and end their session. This action is undoable. OK to procced?'} %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/diners/show.html.erb
<div class="container">
<h1>Walk-in Diner</h1>
<p>
  Name:
  <%= @diner.name %>
</p>
<p>
  Phone:
  <%= @diner.phone %>
</p>
<p>
  Email:
  <%= @diner.email %>
</p>
<p>
  Quanity:
  <%= @diner.party_size %>
</p>
<p>
  Status:
  <%= @diner.status %>
</p>
<p>
  Queue Number:
  <%= @diner.queue_number %>
</p>
<p>
  Table:
  <%= @diner.table_id %>
</p>
<p>
  Special Requests:
  <%= @diner.special_requests %>
</p>
<p>
  Start Time:
  <%= @diner.start_time %>
</p>
<p>
  End Time:
  <%= @diner.end_time %>
</p>
</div>