config/routes.rb
Rails.application.routes.draw do
  # home
  root to: 'restaurants#index'

  # serve websocket cable requests
  mount ActionCable.server, at: '/cable'

  # route for Twilio SMS
  post '/messages/receive' => 'twilio#receive'

  # users
  devise_for :users, path: '/', path_names: {
    sign_up: 'register',
    sign_in: 'login',
    sign_out: 'logout',
    edit: 'account'
  }
  get '/invoices' => 'users#invoices'
  get '/reservations' => 'users#reservations'

  # restaurant management
  get '/dashboard' => 'dashboard#index'

  # restaurants
  resources :restaurants do
    resources :reservations
    resources :menu_items
    resources :tables
    resources :invoices, except: [:new] do
      resources :orders
    end
    # display all orders
    get 'orders' => 'orders#index'

    resources :walkins, except: [:show, :edit]
    get 'public' => 'walkins#public_show'
    post 'public' => 'walkins#public_create'
    get 'public/new' => 'walkins#public_new', as: 'new_public'

    put 'notify/:id' => 'walkins#notify', as: 'notify'
    put 'requeue/:id' => 'walkins#requeue', as: 'requeue'
    put 'seated/:id' => 'walkins#seated', as: 'seated'
    put 'cancelled/:id' => 'diners#cancelled', as: 'cancelled'
    put 'checked_out/:id' => 'diners#checked_out', as: 'checked_out'

    get 'diners' => 'diners#index'
    get 'diners/:id/edit' => 'diners#edit', as: 'edit_diner'
    get 'diners/:id' => 'diners#show', as: 'diner'
    put 'diners/:id' => 'diners#update'

    put 'reset_queue' => 'restaurants#reset_queue'
  end
end

app/controllers/walkins_controller.rb
class WalkinsController < ApplicationController
  include AuthenticateRestaurantUser
  include AddBreadcrumbs
  include FindingTableLogic
  include SendTwilio
  include Format
  before_action :authenticate_user!
  before_action :set_restaurant
  before_action :check_user_is_part_of_restaurant
  before_action :set_walkin, only: %i[show edit update destroy]
  before_action :set_duration
  helper WalkinHelper

  def index
    add_index_breadcrumbs
    @walkins = Reservation.where(restaurant_id: params[:restaurant_id], status: 'queuing').or(Reservation.where(restaurant_id: params[:restaurant_id], status: 'awaiting')).or(Reservation.where(restaurant_id: params[:restaurant_id], status: 'reservation'))
  end

  def create
    create_walkin(walkin_params)

    recommended_table = determine_table(@restaurant, find_aval_tables(@restaurant), @walkin, Time.now, @est_duration)

    if recommended_table
      # Give customer a table if there is one
      update_table_count(recommended_table, @walkin.party_size)

      # Update as 'awating'
      update_customer(@walkin, recommended_table, 'queuing', Time.now, Time.now + @est_duration)

      if @walkin.save!
        redirect_to dashboard_path
      else
        render :new
      end
    else
      # Queue customer if there is no table
      update_customer(@walkin, nil, 'queuing', nil, nil)

      if @walkin.save!
        redirect_to dashboard_path
      else
        render :new
      end
    end
  end

  def new
    add_breadcrumb "Restaurants", :restaurants_path
    add_breadcrumb @restaurant.name, restaurant_path(@restaurant)
    add_breadcrumb "View Current Queue", restaurant_walkins_path(@restaurant)
    @walkin = Reservation.new
  end

  def public_create
    create_walkin(public_params)

    user_reservations = Reservation.where(restaurant_id: @restaurant.id).where(phone: @walkin.phone)
    # Check for multiple entries
    if user_reservations.where(status: ['awaiting', 'queuing', 'dining']).count > 0

      @walkin.destroy
      flash['alert'] = 'This is a duplicated entry and is not permitted. Please contact us if otherwise.'
      redirect_to restaurant_new_public_path(@restaurant)

    elsif user_reservations.where(status: 'reservation').where('start_time < ?', Time.now + 2.hours).count > 0

      @walkin.destroy
      flash['alert'] = 'This entry is not permitted as you already have an upcoming reservation within 2 hours. Please contact us if otherwise.'
      redirect_to restaurant_new_public_path(@restaurant)

    else
      recommended_table = determine_table(@restaurant, find_aval_tables(@restaurant), @walkin, Time.now, @est_duration)

      if recommended_table
        # Give customer a table if there is one
        update_table_count(recommended_table, @walkin.party_size)

        # Update as 'awating' here and send sms if automated
        update_customer(@walkin, recommended_table, 'queuing', Time.now, Time.now + @est_duration)

        sms_queue(@walkin, Reservation.where(restaurant_id: params[:restaurant_id]).where('status = ?', 'queuing').count)

        public_save(@walkin)
      else
        # Queue customer if there is no table
        update_customer(@walkin, nil, 'queuing', nil, nil)

        sms_queue(@walkin, Reservation.where(restaurant_id: params[:restaurant_id]).where('status = ?', 'queuing').count)

        public_save(@walkin)
      end
    end
  end

  def public_save(walkin)
    if walkin.save!
      walkin_name = walkin.name != nil ? walkin.name : ''
      walkin_phone = formatPhone(walkin.phone)
      walkin_start_time = walkin.start_time != nil ? formatOrderDate(walkin.start_time) : ''
      walkin_table_name = walkin.table != nil ? walkin.table.name : ''

      ActionCable.server.broadcast('room_channel', { walkin: walkin.id, queue_number: walkin.queue_number, name: walkin_name, phone: walkin_phone, party_size: walkin.party_size, start_time: walkin_start_time, table_name: walkin_table_name, restaurant: @restaurant.id} )

      redirect_to restaurant_public_path(@restaurant)
    else
      render :public_new
    end
  end

  def public_new
    @walkin = Reservation.new
    render 'layouts/public_walkin_new', layout: false
  end

  def public_show
    render 'layouts/public_walkin', layout: false
  end

  # def edit; end

  # def show; end

  # def update; end

  def update_save
    if @walkin.save!
      redirect_to restaurant_walkins_path(@restaurant)
    else
      flash['alert'] = 'Error. Unable to save update.'
      render :edit
    end
  end

  # def destroy
  #   @walkin.destroy
  #   redirect_to restaurant_walkins_path(@restaurant)
  # end

  def notify
    if Reservation.find(params[:id]) && Restaurant.find(params[:restaurant_id])
      walkin = Reservation.find(params[:id])
      walkin.status = 'awaiting'
      if walkin.save!
        sms_awaiting(walkin)
        flash['notice'] = "#{walkin.name} was notified"
        redirect_to dashboard_path
      else
        flash['alert'] = 'Error 500. Unable to update status'
        redirect_to dashboard_path
      end
    else
      flash['alert'] = 'Error. Unable to find reservation or restaurant in DB.'
      redirect_to dashboard_path
    end
  end

  def requeue
    if Reservation.find(params[:id]) && Restaurant.find(params[:restaurant_id])
      walkin = Reservation.find(params[:id])
      walkin.queue_number = walkin.restaurant.next_queue_number
      set_next_queue_number(walkin.restaurant)
      if walkin.save!
        sms_requeue(walkin)
        flash['alert'] = "#{walkin.name}(##{walkin.queue_number}) was requeued"
        redirect_to dashboard_path
      else
        flash['alert'] = 'Error 500. Unable to update'
        redirect_to dashboard_path
      end
    else
      flash['alert'] = 'Error. Unable to find reservation or restaurant in DB.'
      redirect_to dashboard_path
    end
  end

  def seated
    if Reservation.find(params[:id]) && Restaurant.find(params[:restaurant_id])
      diner = Reservation.find(params[:id])
      old_status = diner.status
      diner.status = 'dining'
      diner.start_time = Time.now
      diner.end_time = Time.now + @est_duration
      diner.table.capacity_current = diner.party_size
      diner.save!
      diner.table.save!
      if old_status == 'reservation'
        flash['notice'] = "#{diner.name}(Reservation ##{diner.id}) has checked into the restaurant"
        redirect_to dashboard_path
      else
        flash['notice'] = "#{diner.name}(##{diner.queue_number}) has checked into the restaurant"
        redirect_to dashboard_path
      end

    else
      flash['alert'] = 'Error. Unable to find reservation or restaurant in DB.'
      redirect_to dashboard_path
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def set_walkin
    @walkin = Reservation.find(params[:id])
  end

  # Create Walkin Person's Restaurant & Queue Number
  def create_walkin(params)
    @walkin = Reservation.new(params)
    @walkin.restaurant_id = @restaurant.id
    @walkin.queue_number = @restaurant.next_queue_number
    if @walkin.phone
      find_user(@walkin)
    end
    set_next_queue_number(@restaurant)
  end

  def set_next_queue_number(restaurant)
    restaurant.next_queue_number += 1
    restaurant.save
  end

  # Set Details of Walkin User
  def find_user(walkin)
    user = User.where(phone: walkin.phone)
    if user.count == 1
      walkin.user_id = user.pluck(:id)[0]
      walkin.name = user.pluck(:name)[0]
      walkin.email = user.pluck(:email)[0]
      walkin.save!
    else
      walkin.name = 'Customer'
    end
  end

  # Find Available Tables For New Customer
  def find_aval_tables(restaurant)
    # aval_tables = Table.where(restaurant_id: restaurant.id).where('capacity_current = ?', 0)

    tables_occupied = Reservation.where(restaurant_id: @restaurant.id).where(status: 'dining').where.not(table_id: nil).map do |reservation|
      reservation.table
    end
    aval_tables = @restaurant.tables - tables_occupied
  end

  # Change Table's new capacity once customer is assigned
  def update_table_count(table, filled)
    table.capacity_current = filled
    table.save!
  end

  def update_customer(customer, recommended_table, new_status, new_start_time, new_end_time)
    customer.status = new_status
    if recommended_table
      customer.table_id = recommended_table.id
    end
    if new_start_time
      customer.start_time = new_start_time
    end
    if new_end_time
      customer.end_time = new_end_time
    end
  end

  def public_params
    params.require(:reservation).permit(:phone, :party_size)
  end

  def walkin_params
    params.require(:reservation).permit(:name, :phone, :email, :party_size, :special_requests, :status)
  end
end

app/helpers/walkin_helper.rb
module WalkinHelper
  include Format
end

app/views/walkins/edit.html.erb
<div class="container">
<h1>Edit Queuing Diner</h1>

<%= form_for @walkin, url: restaurant_walkin_path(@restaurant, @walkin), html: {method: :put} do |f| %>
  <p>
    Name:
    <%= @walkin.name %>
  </p>

  <p>
    Phone:
    <%= @walkin.phone %>
  </p>

  <p>
    Email:
    <%= @walkin.email %>
  </p>

  <p>
    Queue Number:
    <%= @walkin.queue_number %>
  </p>

  <% if @walkin.status == 'queuing' %>
  <% if @walkin.table %>
    <p>
      <%= f.label :status, "Status" %>
      <%= f.select(:status, [['Cancelled','cancelled'],['Queuing','queuing'], ['Awaiting','awaiting']])%>
    </p>
  <% else %>
    <p>
      <%= f.label :status, "Status" %>
      <%= f.select(:status, [['Cancelled','cancelled'],['Queuing','queuing']])%>
    </p>
  <% end %>

  <% elsif @walkin.status == 'reservation' %>
  <p>
    <%= f.label :status, "Status" %>
    <%= f.select(:status, [['Cancelled','cancelled'],['Reservation','reservation'], ['Dining','dining']])%>
  </p>
  <% end %>

  <% if @walkin.status == 'queuing' %>
    <p>
      <%= f.label :party_size, "Number of Diners" %>
      <% if @restaurant.tables.count > 0 %>
        <%= f.select :party_size,[*1..@restaurant.tables.reject{|y| y[:capacity_total] == nil}.max_by{|x| x[:capacity_total]}.capacity_total]%>
      <% else %>
        <%= f.select :party_size,[0]%>
      <% end %>
    </p>
  <% else %>
    <p>
      Party Size:
      <%= @walkin.party_size %>
    </p>
  <% end %>

  <p>
    Table:
    <%= @walkin.table_id %>
  </p>

  <p>
    <%= f.label :special_requests, "Special Requests" %>
    <%= f.text_field :special_requests, placeholder: "Special Requests"%>
  </p>

  <p>
    Start Time:
    <%= @walkin.start_time %>
  </p>

  <p>
    End Time:
    <%= @walkin.end_time %>
  </p>

  <%= f.submit "Submit" %>
<% end %>
</div>

app/views/walkins/index.html.erb
<div class="container">
<h1>Current Queue</h1>

<p>Current Time: <%= formatOrderDate(Time.now)%></p>
<%= link_to 'Add New Customer', new_restaurant_walkin_path(@restaurant, @walkin), class: 'waves-effect waves-light btn light-blue lighten-3'%>

<h2>Queuing</h2>
<table class="striped centered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Quantity</th>
      <th>Status</th>
      <th>Queue Number</th>
      <th>Table Assigned</th>
      <th>Requests</th>
      <th>Est Start Time</th>
      <th>Est End Time</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @walkins.where(status:'queuing').each do |walkin| %>
    <tr>
      <td><%= link_to walkin.name, restaurant_edit_diner_path(@restaurant.id, walkin) %></td>
      <!-- <td><%= walkin.name %></td> -->
      <td><%= walkin.phone %></td>
      <td><%= walkin.email %></td>
      <td><%= walkin.party_size %></td>
      <td>
        <% if walkin.status == 'awaiting' %>
        <font color="red"><b><%= walkin.status %></b></font>
        <% else %>
        <%= walkin.status %>
        <% end %>
      </td>
      <td><%= walkin.queue_number %></td>

      <td>
      <% if walkin.table_id %>
      <%= Table.find(walkin.table_id).name %>
      <% end %>
      </td>

      <td><%= walkin.special_requests %></td>
      <td>
        <% if walkin.start_time %>
        <%= formatOrderDate(walkin.start_time.getlocal('+08:00')) %>
        <% end %>
      </td>
      <td>
        <% if walkin.end_time %>
        <% if Time.now > walkin.end_time %>
        <font color="red"><b><%= formatOrderDate(walkin.end_time.getlocal('+08:00')) %></b></font>
        <% else %>
        <%= formatOrderDate(walkin.end_time.getlocal('+08:00')) %>
        <% end %>
        <% end %>
      </td>
      <td>
        <% if walkin.table %>
        <%= link_to 'Notify', restaurant_notify_path(@restaurant, walkin), method: :put%>
        <% elsif walkin.queue_number + 1 != walkin.restaurant.next_queue_number %>
        <%= link_to 'Requeue', restaurant_requeue_path(@restaurant, walkin), method: :put, data: { confirm: 'This will send the customer to the back of the queue. This action is undoable. OK to procced?'} %>
        <% end %>
      </td>
    <% end %>
  </tbody>
</table>

<h2>Reservations</h2>
<table class="striped centered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Quantity</th>
      <th>Status</th>
      <th>Queue Number</th>
      <th>Table Assigned</th>
      <th>Requests</th>
      <th>Est Start Time</th>
      <th>Est End Time</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @walkins.where(status:'reservation').each do |walkin| %>
    <tr>
      <td><%= link_to walkin.name, restaurant_edit_diner_path(@restaurant.id, walkin) %></td>
      <!-- <td><%= walkin.name %></td> -->
      <td><%= walkin.phone %></td>
      <td><%= walkin.email %></td>
      <td><%= walkin.party_size %></td>

      <td>
        <% if walkin.status == 'awaiting' %>
        <font color="red"><b><%= walkin.status %></b></font>
        <% else %>
        <%= walkin.status %>
        <% end %>
      </td>

      <td><%= walkin.queue_number %></td>

      <td>
      <% if walkin.table_id %>
      <%= Table.find(walkin.table_id).name %>
      <% end %>
      </td>

      <td><%= walkin.special_requests %></td>

      <td>
        <% if walkin.start_time %>
        <%= formatOrderDate(walkin.start_time.getlocal('+08:00')) %>
        <% end %>
      </td>

      <td>
        <% if walkin.end_time %>
        <% if Time.now > walkin.end_time %>
        <font color="red"><b><%= formatOrderDate(walkin.end_time.getlocal('+08:00')) %></b></font>
        <% else %>
        <%= formatOrderDate(walkin.end_time.getlocal('+08:00')) %>
        <% end %>
        <% end %>
      </td>

      <td>
        <%= link_to 'Seated', restaurant_seated_path(@restaurant, walkin), method: :put %>
      </td>

    </tr>
    <% end %>
  </tbody>
</table>

<h2>Notified</h2>
<table class="striped centered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Quantity</th>
      <th>Status</th>
      <th>Queue Number</th>
      <th>Table Assigned</th>
      <th>Requests</th>
      <th>Est Start Time</th>
      <th>Est End Time</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @walkins.where(status:'awaiting').each do |walkin| %>
    <tr>
      <td><%= link_to walkin.name,
      restaurant_edit_diner_path(@restaurant.id, walkin) %></td>
      <td><%= walkin.phone %></td>
      <td><%= walkin.email %></td>
      <td><%= walkin.party_size %></td>

      <td>
        <% if walkin.status == 'awaiting' %>
        <font color="red"><b><%= walkin.status %></b></font>
        <% else %>
        <%= walkin.status %>
        <% end %>
      </td>

      <td><%= walkin.queue_number %></td>

      <td>
      <% if walkin.table_id %>
      <%= Table.find(walkin.table_id).name %>
      <% end %>
      </td>

      <td><%= walkin.special_requests %></td>
      <td>
        <% if walkin.start_time %>
        <%= formatOrderDate(walkin.start_time.getlocal('+08:00')) %>
        <% end %>
      </td>
      <td>
        <% if walkin.end_time %>
        <% if Time.now > walkin.end_time %>
        <font color="red"><b><%= formatOrderDate(walkin.end_time.getlocal('+08:00')) %></b></font>
        <% else %>
        <%= formatOrderDate(walkin.end_time.getlocal('+08:00')) %>
        <% end %>
        <% end %>
      </td>

      <td>
        <%= link_to 'Seated', restaurant_seated_path(@restaurant, walkin), method: :put %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/walkins/new.html.erb
<div class="container">
<h1><%= @restaurant.name%></h1>
<h2>Add New Walk-in Customer</h2>

<%= form_for @walkin, url: restaurant_walkins_path(@restaurant), html: {method: :post} do |f| %>

  <p>
    Queue Number:
    <%= @restaurant.next_queue_number %>
  </p>

  <div class="field">
    <%= f.label :name, "Name" %>
    <%= f.text_field :name, placeholder: "Customer " + @restaurant.next_queue_number.to_s , value: "Customer " + @restaurant.next_queue_number.to_s, :required => true %>
  </div>

    <%= f.label :party_size, "Number of Diners" %>
    <div class="res-field">
    <% if @restaurant.tables.count > 0 %>
      <%= f.select :party_size,[*1..@restaurant.tables.reject{|y| y[:capacity_total] == nil}.max_by{|x| x[:capacity_total]}.capacity_total]%>
    <% else %>
      <%= f.select :party_size,[0]%>
    <% end %>
  </div>

  <%= f.submit "Submit", class: 'waves-effect waves-light btn light-blue lighten-3' %>

<% end %>
</div>

app/views/walkins/show.html.erb
<div class="container">
<h1>Walkin Diner</h1>
<p>
  Name:
  <%= @walkin.name %>
</p>
<p>
  Phone:
  <%= @walkin.phone %>
</p>
<p>
  Email:
  <%= @walkin.email %>
</p>
<p>
  Quanity:
  <%= @walkin.party_size %>
</p>
<p>
  Status:
  <%= @walkin.status %>
</p>
<p>
  Queue Number:
  <%= @walkin.queue_number %>
</p>
<p>
  Table:
  <%= Table.find(@walkin.table_id).name %>
</p>
<p>
  Special Requests:
  <%= @walkin.special_requests %>
</p>
<p>
  Start Time:
  <%= @walkin.start_time %>
</p>
<p>
  End Time:
  <%= @walkin.end_time %>
</p>
</div>